// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: user.proto

package user_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserServiceRPC_GetUserProfile_FullMethodName  = "/userservice_v1.UserServiceRPC/GetUserProfile"
	UserServiceRPC_GetUserProfiles_FullMethodName = "/userservice_v1.UserServiceRPC/GetUserProfiles"
)

// UserServiceRPCClient is the client API for UserServiceRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceRPCClient interface {
	GetUserProfile(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error)
	GetUserProfiles(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error)
}

type userServiceRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceRPCClient(cc grpc.ClientConnInterface) UserServiceRPCClient {
	return &userServiceRPCClient{cc}
}

func (c *userServiceRPCClient) GetUserProfile(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProfileResponse)
	err := c.cc.Invoke(ctx, UserServiceRPC_GetUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceRPCClient) GetUserProfiles(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProfileResponse)
	err := c.cc.Invoke(ctx, UserServiceRPC_GetUserProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceRPCServer is the server API for UserServiceRPC service.
// All implementations must embed UnimplementedUserServiceRPCServer
// for forward compatibility.
type UserServiceRPCServer interface {
	GetUserProfile(context.Context, *GetUserRequest) (*GetUserProfileResponse, error)
	GetUserProfiles(context.Context, *GetUserRequest) (*GetUserProfileResponse, error)
	mustEmbedUnimplementedUserServiceRPCServer()
}

// UnimplementedUserServiceRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceRPCServer struct{}

func (UnimplementedUserServiceRPCServer) GetUserProfile(context.Context, *GetUserRequest) (*GetUserProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (UnimplementedUserServiceRPCServer) GetUserProfiles(context.Context, *GetUserRequest) (*GetUserProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserProfiles not implemented")
}
func (UnimplementedUserServiceRPCServer) mustEmbedUnimplementedUserServiceRPCServer() {}
func (UnimplementedUserServiceRPCServer) testEmbeddedByValue()                        {}

// UnsafeUserServiceRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceRPCServer will
// result in compilation errors.
type UnsafeUserServiceRPCServer interface {
	mustEmbedUnimplementedUserServiceRPCServer()
}

func RegisterUserServiceRPCServer(s grpc.ServiceRegistrar, srv UserServiceRPCServer) {
	// If the following call pancis, it indicates UnimplementedUserServiceRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserServiceRPC_ServiceDesc, srv)
}

func _UserServiceRPC_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceRPCServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserServiceRPC_GetUserProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceRPCServer).GetUserProfile(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserServiceRPC_GetUserProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceRPCServer).GetUserProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserServiceRPC_GetUserProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceRPCServer).GetUserProfiles(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserServiceRPC_ServiceDesc is the grpc.ServiceDesc for UserServiceRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserServiceRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userservice_v1.UserServiceRPC",
	HandlerType: (*UserServiceRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserProfile",
			Handler:    _UserServiceRPC_GetUserProfile_Handler,
		},
		{
			MethodName: "GetUserProfiles",
			Handler:    _UserServiceRPC_GetUserProfiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
